# -*- coding: utf-8 -*-
"""SVM_MFCC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VduzHeBmIV6iuqB6jLtZr8zysr1AnSxS
"""

import sklearn
from sklearn import svm
import numpy as np
from sklearn.impute import SimpleImputer
Train_X = np.array(training_df.feature.tolist())
Train_Y = np.array(training_df.class_label.tolist())
Test_X = np.array(testing_df.feature.tolist())
Test_Y = np.array(testing_df.class_label.tolist())

col_mean = np.nanmean(Train_X, axis = 0) 
inds = np.where(np.isnan(Train_X)) 
Train_X[inds] = np.take(col_mean, inds[1]) 

col_x = np.nanmean(Test_X,axis = 0)
inds = np.where(np.isnan(Test_X)) 
Test_X[inds] = np.take(col_x, inds[1]) 


svm_classifier = svm.SVC(kernel='rbf', C=10, tol = 0.001)
svm_classifier.fit(Train_X, Train_Y)

y_pred = svc.predict(Test_X)
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(Test_Y, y_pred))

from sklearn.metrics import classification_report
print(classification_report(Test_Y,y_pred))