# -*- coding: utf-8 -*-
"""SVM_Spect.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pb-g_HiYPjPIk8p_LW1zyj6sscqF5ApM
"""

from google.colab import drive
drive.mount('/content/drive')

from sklearn import svm
# reference : https://github.com/CheshtaK/Image-Classification/blob/master/Image%20Classification.ipynb

import numpy as np
import os
from pathlib import Path

############################## Read Test Data #######################3
p = Path("/content/drive/My Drive/MCA/Assignment 2/Dataset/test_spect")
dirs = p.glob("*")
labels_dict = {'zero':0, 'one':1, 'two':2, 'three': 3,'four': 4, 'five': 5, 'six': 6, 'seven': 7, 'eight': 8, 'nine': 9} 

image_data = []
labels = []    

for folder_dir in dirs:
    label = str(folder_dir).split("/")[-1]
    
    for img_path in folder_dir.glob("*.png"):
        img = image.load_img(img_path, target_size=(64,64))
        img_array = image.img_to_array(img)
        image_data.append(img_array)
        labels.append(labels_dict[label])

test_X = np.array(image_data, dtype='float32')/255.0
test_Y = np.array(labels)

############################## Read Trai Data #######################3
train_path = Path("/content/drive/My Drive/MCA/Assignment 2/Dataset/train_spect")
dirs = train_path.glob("*")
labels_dict = {'eight': 8, 'nine': 9} 

train_image_data = []
train_labels = []    

for folder_dir in dirs:
    label = str(folder_dir).split("/")[-1]
    
    for img_path in folder_dir.glob("*.png"):
        img = image.load_img(img_path, target_size=(64,64))
        img_array = image.img_to_array(img)
        train_image_data.append(img_array)
        train_labels.append(labels_dict[label])

train_path = Path("/content/drive/My Drive/MCA/Assignment 2/Dataset/test_1")
dirs = train_path.glob("*")
labels_dict = {'zero': 0, 'one': 1} 
for folder_dir in dirs:
    label = str(folder_dir).split("/")[-1]
    
    for img_path in folder_dir.glob("*.png"):
        img = image.load_img(img_path, target_size=(64,64))
        img_array = image.img_to_array(img)
        train_image_data.append(img_array)
        train_labels.append(labels_dict[label])

train_path = Path("/content/drive/My Drive/MCA/Assignment 2/Dataset/test_2")
dirs = train_path.glob("*")
labels_dict = {'two': 2, 'three': 3} 
for folder_dir in dirs:
    label = str(folder_dir).split("/")[-1]
    
    for img_path in folder_dir.glob("*.png"):
        img = image.load_img(img_path, target_size=(64,64))
        img_array = image.img_to_array(img)
        train_image_data.append(img_array)
        train_labels.append(labels_dict[label])

trainX = np.array(train_image_data, dtype='float32')/255.0
trainY = np.array(train_labels)

re_size = trainX.shape[0]
trainX = trainX.reshape(re_size,-1)
svm_classifier = svm.SVC(kernel='rbf', C=10, tol = 0.01)
svm_classifier.fit(trainX, trainY)

re_size = test_X.shape[0]
test_X = test_X.reshape(re_size,-1)
y_pred = svm_classifier.predict(testX)

from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(test_Y, y_pred))

from sklearn.metrics import classification_report
print(classification_report(test_Y,y_pred))

